default: &default
  version: "0.19.1-beta"
  server_name: <%= ENV['SERVER_NAME'] || "localhost:3000" %>
  server_protocol: <%= ENV['SERVER_PROTOCOL'] || "http" %>
  twitter_key: <%= ENV['TWITTER_KEY'] || "" %>
  twitter_secret: <%= ENV['TWITTER_SECRET'] || "" %>
  facebook_key: <%= ENV['FACEBOOK_KEY'] || "" %>
  facebook_secret: <%= ENV['FACEBOOK_SECRET'] || "" %>
  google_oauth2_key: <%= ENV['GOOGLE_OAUTH2_KEY'] || "" %>
  google_oauth2_secret: <%= ENV['GOOGLE_OAUTH2_SECRET'] || "" %>
  wordpress_oauth2_key: <%= ENV['WORDPRESS_OAUTH2_KEY'] || "" %>
  wordpress_oauth2_secret: <%= ENV['WORDPRESS_OAUTH2_SECRET'] || "" %>
  wordpress_oauth2_site: <%= ENV['WORDPRESS_OAUTH2_SITE'] || "" %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] || "" %>

maps: &maps
  map_tiles_provider: "//{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
  map_tiles_provider_attribution: "&copy; <a href=\"http://osm.org/copyright\">OpenStreetMap</a> contributors"

apis: &apis
  census_api_end_point: ""
  census_api_institution_code: ""
  census_api_portal_name: ""
  census_api_user_code: ""
  sms_end_point:  ""
  sms_username: ""
  sms_password: ""

http_basic_auth: &http_basic_auth
  http_basic_auth: true

development:
  http_basic_username: "dev"
  http_basic_password: "pass"
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] || "Whatever for development" %>
  <<: *default
  <<: *maps

test:
  <<: *default
  <<: *maps

staging:
  rollbar_server_token: ""
  http_basic_username: ""
  http_basic_password: ""
  managers_url: ""
  managers_application_key: ""
  server_protocol: <%= ENV['SERVER_PROTOCOL'] || "https" %>
  <<: *default
  <<: *maps
  <<: *apis

preproduction:
  rollbar_server_token: ""
  http_basic_username: ""
  http_basic_password: ""
  managers_url: ""
  managers_application_key: ""
  server_protocol: <%= ENV['SERVER_PROTOCOL'] || "https" %>
  <<: *default
  <<: *maps
  <<: *apis

production:
  rollbar_server_token: ""
  http_basic_username: ""
  http_basic_password: ""
  managers_url: ""
  managers_application_key: ""
  server_protocol: <%= ENV['SERVER_PROTOCOL'] || "https" %>
  <<: *default
  <<: *maps
  <<: *apis
